name: Setup Files
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python setup.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "
